apiVersion: v1
kind: Service
metadata:
  name: usermanagement
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30008
 selector:
  app: user-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  selector:
    matchLabels:
      app: user-management
  replicas: 3
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management-microservice
        imagePullPolicy: Always
        image: ansvohra/user-management
        ports:
        - containerPort: 5000